# ╭─────────────────────ImplementationGuide-hl7.fhir.uv.med-list-guidance.json─────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.med-list-guidance
canonical: http://hl7.org/fhir/uv/med-list-guidance
version: 0.1.0
name: HL7PharmacyMedicationListGuidance
title: "HL7 Pharmacy: Medication List Guidance"
status: active
publisher:
  name: HL7 Pharmacy
  url: http://www.hl7.org/Special/committees/pharmacy
  email: pharmacy@lists.hl7.org
description: Guidance to Implementation Guide authors who are incorporating Medication
  List(s) of some context in their guide.
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Introduction: index.html
  Guidance: guidance.html
  List Contexts:
    Prescribing Lists: prescribemeds.html
    Dispensing Lists: dispensemeds.html
    Medication Administration Lists: medadmin.html
    Medication Administration History: medadminhistory.html
    Patient View of Medications: patientview.html
    Medication Reconciliation: medrec.html
    Blister Packing Lists: blisterpack.html

pages:
  index.md:
    title: Introduction
  guidance.md:
    title: Guidance
  prescribemeds.md:
    title: Prescribing Lists
  dispensemeds.md:
    title: Dispensing Lists
  medadmin.md:
    title: Medication Administration Lists
  medadminhistory.md:
    title: Medication Administration History
  patientview.md:
    title: Patient View of Medications
  medrec.md:
    title: Medication Reconciliation
  blisterpack.md:
    title: Blister Packing Lists
