# ╭─────────────────────ImplementationGuide-hl7.fhir.uv.med-list-guidance.json─────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.med-list-guidance
canonical: http://hl7.org/fhir/uv/med-list-guidance
version: 0.1.0
name: HL7PharmacyMedicationListGuidance
title: "HL7 Pharmacy: Medication List Guidance"
status: active
publisher:
  name: HL7 Pharmacy
  url: http://www.hl7.org/Special/committees/pharmacy
  email: pharmacy@lists.hl7.org
description: Guidance to Implementation Guide authors who are incorporating Medication
  List(s) of some context in their guide.
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To control the ig.ini using this config, uncomment and set the "template" property.           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
template: hl7.fhir.template

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Introduction: index.html
  List Contexts:
    Patient View of Medications: patientview.html
    Discharge Medications: dischargemeds.html
  Downloads: downloads.html

pages:
  index.md:
    title: Introduction
  patientview.md:
    title: Patient View of Medications
  dischargemeds.md:
    title: Discharge Medications
  downloads.md:
    title: Downloads
		